export enum PERMISSION {
  'USER:MANAGE',
  'USER:READ',
  'USER:CREATE',
  'USER:UPDATE',
  'USER:DELETE',

  'ROLE:MANAGE',
  'ROLE:READ',
  'ROLE:CREATE',
  'ROLE:UPDATE',
  'ROLE:DELETE',

  'EXAMPLE:MANAGE',
  'EXAMPLE:READ',
  'EXAMPLE:CREATE',
  'EXAMPLE:UPDATE',
  'EXAMPLE:DELETE',
}
